config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :areas do
    # 単数形リソース(resource)なので通常は単数形で書くが、複数のfoodsを取り扱うため複数形で定義している
    resource :foods, only: [:new, :create, :edit, :update], module: :areas, controller: :foods
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'posts#index'
  resources :comics, except: [:destroy]
  resources :posts, only: [:index] do
    collection do
      get 'google_map'
      post 'sort'
      get 'send_sample_mail'
      get 'send_now_sample_mail'
      get 'csv_export'
      get :zip_export
    end
  end

  namespace :api do
    get 'postal_code_search/search'
  end

  # コマンドでcontrollerファイルをディレクトリ階層いかに生成した場合、以下のようにルーティングが自動記述される。
  # namespace ディレクトリ名でURLを"/ディレクトリ名/コントローラー名", 見に行くコントローラーも"/ディレクトリ名/コントローラー名"になる。実装によってscopeやscope moduleなどを使い分けるとよい
  namespace :hoge do
    # get 'posts/index'
    resources :posts, only: [:index]
  end

  resources :tweets, only: [:index, :new, :create, :edit, :update]

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  mount Sidekiq::Web => '/sidekiq'

  # Bootstrap JavaScript Bundle with Popper
  direct :bootstrap_javascript do
    'https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js'
  end
  # Bootstrap Icons
  direct :bootstrap_icons_css do
    'https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css'
  end

  # Slick(JavaScriptはimportmapで導入)
  direct :slick_css do
    'https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css'
  end
  direct :slick_theme_css do
    'https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css'
  end
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  has_many :tweet_tags, dependent: :destroy
  has_one :tweet_image, dependent: :destroy

  accepts_nested_attributes_for :tweet_tags, allow_destroy: true
  # reject_ifオプションで指定した条件でtrueになった時にその子モデルを生成しないように設定している
  accepts_nested_attributes_for :tweet_image, allow_destroy: true, reject_if: :storage_file_attached?

  validates :title, :text, presence: true
  # チェックボックスのON/OFFの検証をする。(パラメーターにその値が含まれない場合などはバリデーションチェックはしない)
  # 指定した値はDBに存在しなくてもattr_accessorで設定した場合と同じになる。
  # 利用規約の同意などで使える。
  validates :accept, acceptance: true

  delegate :attached?, to: :tweet_image, allow_nil: true

  private

  # 作成・編集のパラメーターにtweet_images.storage_fileがないときにtweet_imageを作成しないためのメソッド
  def storage_file_attached?(attributes)
    # !attached? でも可
    attributes[:storage_file].blank?
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:new, :create, :edit, :update]
  before_action :set_tweet_image, only: [:new, :edit]

  def index
    @tweets = Tweet.all.includes(
      :tweet_tags, tweet_image: [storage_file_attachment: :blob]
    )
  end

  def new; end

  def create
    @tweet.assign_attributes(tweet_params)
    if @tweet.save
      redirect_to action: :index
    else
      set_tweet_image
      render :new
    end
  end

  def edit; end

  def update
    if @tweet.update(tweet_params)
      redirect_to action: :index
    else
      set_tweet_image
      render :edit
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(
      :title,
      :text,
      :accept,
      tweet_image_attributes: [:id, :_destroy, :storage_file],
      tweet_tags_attributes: [:id, :_destroy, :name]
    )
  end

  # バリデーションエラー時に画像が保存されず保存しようとした画像ファイルもformからリセットされてしまい、画像プレビューが表示できない
  # 解決方法としては二つ考えられる
  # 非同期処理にしてjsでページ遷移のコントロールをする、またはActiveStorageのダイレクトアップロード機能を使う
  def set_tweet
    @tweet = params[:id] ? Tweet.find(params[:id]) : Tweet.new
  end

  # 画像のパラメーターなしの時にcreateとupdateアクションの前に発動するとbuild_tweet_imageによって空のtweet_imageが作成される
  # (accepts_nested_attributes_forのreject_ifオプションを指定してもbuildしてしまうとレコードが作成されてしまう)
  # よってバリデーションエラー時のelseの分岐時だけrenderの前で発動させている
  def set_tweet_image
    @tweet_image = @tweet.tweet_image.nil? ? @tweet.build_tweet_image : @tweet.tweet_image
  end
end

app/views/tweets/_form.html.erb
<main class="p-4">
  <%= form_with model: tweet, local: true, data: { controller: 'nested-form', nested_form_wrapper_selector_value: '.nested-form-wrapper' } do |f| %>
    <div class="m-1">
      <%= f.label :title, style: 'display: block;' %>
      <%= f.text_field :title %>
    </div>
    <div class="m-1">
      <%= f.label :text, style: 'display: block;' %>
      <%= f.text_area :text %>
    </div>

    <template data-nested-form-target="template">
      <%= f.fields_for :tweet_tags, TweetTag.new, child_index: 'NEW_RECORD' do |ff| %>
        <%= render 'tweet_tag_form', ff: ff %>
      <% end %>
    </template>

    <%= f.fields_for :tweet_tags do |ff| %>
      <%= render 'tweet_tag_form', ff: ff %>
    <% end %>

    <!-- Inserted elements will be injected before that target. -->
    <div data-nested-form-target="target"></div>

    <button type="button" data-action="nested-form#add">Add todo</button>

    <div class="m-1" data-controller="image-form">
      <%= f.fields_for :tweet_image, @tweet_image do |ff| %>
        <%= ff.label :storage_file, style: 'display: block;' %>
        <!-- direct_upload: true でバリデーションエラー時にも先んじて紐付けなしでblobに画像を保存する -->
        <%= ff.file_field :storage_file,
                          direct_upload: true,
                          data: { action: 'input->image-form#preview', image_form_target: 'inputFile' } %>

        <%= ff.hidden_field :_destroy, data: { image_form_target: 'removeImageFlag' } %>

        <div class="d-flex">
          <% if @tweet_image.attached? %>
            <div class="me-5" id="currentImageWrapper">
              <p>現在の画像</p>
              <%#= @tweet.tweet_image.storage_file.filename でファイル名を表示できる %>
              <%= image_tag @tweet_image.storage_file, class: 'tweet-image' %>
              <%= button_tag '画像を削除する', type: 'button',
                             data: { action: 'click->image-form#removeImage', image_form_target: 'removeImageButton' } %>
            </div>
          <% end %>

          <template data-image-form-target="newImage">
            <p>新しい画像</p>
            <%= image_tag '', class: 'tweet-image' %>
            <%= button_tag 'キャンセル', type: 'button', data: { action: 'click->image-form#cancelNewImage' } %>
          </template>
          <div data-image-form-target="newImageWrapper"></div>
        </div>
      <% end %>
    </div>

    <div class="m-1">
      <%= f.label :accept %>
      <%= f.check_box :accept %>
    </div>

    <div class="m-1">
      <%= f.submit %>
    </div>
  <% end %>
</main>

app/views/tweets/_tweet_tag_form.html.erb
<div class="nested-form-wrapper" data-new-record="<%= ff.object.new_record? %>">
  <div class="m-1">
    <%= ff.label :name, style: 'display: block;' %>
    <%= ff.text_field :name %>
  </div>

  <button type="button" data-action="nested-form#remove">Remove todo</button>

  <%= ff.hidden_field :_destroy %>
</div>

app/views/tweets/edit.html.erb
<%= render 'form', tweet: @tweet %>

<% breadcrumb :tweet_edit %>
<%= render 'shared/breadcrumb' %>

app/views/tweets/index.html.erb
<main class="p-4">
  <div class="mb-5">
    <%= link_to '新規作成', new_tweet_path %>
  </div>

  <div id="tweets">
    <% @tweets.each do |tweet| %>
      <div class="m-2">
        <div><%= Tweet.human_attribute_name(:title) %></div>
        <div><%= tweet.title %></div>
        <div><%= Tweet.human_attribute_name(:text) %></div>
        <div class="textarea"><%= tweet.text %></div>
        <% if tweet.tweet_tags.present? %>
          <div><%= TweetTag.model_name.human %></div>
        <% end %>
        <% tweet.tweet_tags.each do |tag| %>
          <div><%= "##{tag.name}" %></div>
        <% end %>

        <div><%= TweetImage.model_name.human %></div>
        <div>
          <%= image_tag tweet.tweet_image.storage_file, class: 'tweet-image' if tweet.attached? %>
        </div>

        <div><%= link_to '編集', edit_tweet_path(tweet) %></div>
      </div>
    <% end %>
  </div>
</main>

<% breadcrumb :tweet_index %>
<%= render 'shared/breadcrumb' %>

app/views/tweets/new.html.erb
<%= render 'form', tweet: @tweet %>

<% breadcrumb :tweet_new %>
<%= render 'shared/breadcrumb' %>