config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :areas do
    # 単数形リソース(resource)なので通常は単数形で書くが、複数のfoodsを取り扱うため複数形で定義している
    resource :foods, only: [:new, :create, :edit, :update], module: :areas, controller: :foods
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'posts#index'
  resources :comics, except: [:destroy]
  resources :posts, only: [:index] do
    collection do
      get 'google_map'
      post 'sort'
      get 'send_sample_mail'
      get 'send_now_sample_mail'
      get 'csv_export'
      get :zip_export
    end
  end

  namespace :api do
    get 'postal_code_search/search'
  end

  # コマンドでcontrollerファイルをディレクトリ階層いかに生成した場合、以下のようにルーティングが自動記述される。
  # namespace ディレクトリ名でURLを"/ディレクトリ名/コントローラー名", 見に行くコントローラーも"/ディレクトリ名/コントローラー名"になる。実装によってscopeやscope moduleなどを使い分けるとよい
  namespace :hoge do
    # get 'posts/index'
    resources :posts, only: [:index]
  end

  resources :tweets, only: [:index, :new, :create, :edit, :update]

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  mount Sidekiq::Web => '/sidekiq'

  # Bootstrap JavaScript Bundle with Popper
  direct :bootstrap_javascript do
    'https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js'
  end
  # Bootstrap Icons
  direct :bootstrap_icons_css do
    'https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css'
  end

  # Slick(JavaScriptはimportmapで導入)
  direct :slick_css do
    'https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css'
  end
  direct :slick_theme_css do
    'https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css'
  end
end

app/models/comic.rb
class Comic < ApplicationRecord
  has_many :genres, dependent: :destroy
hoge = hoge
  with_options presence: true do
    validates :title
    validates :author
  end
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  def index
    @comics = Comic.all.includes(:genres).order(created_at: :desc)
  end

  def new
    @comic_genre = ComicGenreForm.new
  end

  def create
    @comic_genre = ComicGenreForm.new(comic_genre_params)
    if @comic_genre.save
      redirect_to action: :index
    else
      render :new
    end
  end

  def edit
    @comic_genre = ComicGenreForm.new(comic_id: params[:id])
  end

  def update
    @comic_genre = ComicGenreForm.new(comic_genre_params, comic_id: params[:id])
    if @comic_genre.update(comic_genre_params)
      redirect_to comics_path
    else
      render :edit
    end
  end

  private

  def comic_genre_params
    params.require(:comic_genre).permit(comic: [:title, :author], genres: :name)
  end
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/views/comics/_form.html.erb
<%= form_with model: @comic_genre, url: @comic_genre.comic, local: true do |f| %>
  <%= fields_for 'comic_genre[comic]', f.object.comic do |ff| %>
    <div>
      <%= ff.label :title %>
      <%= ff.text_field :title %>
    </div>
    <div>
      <%= ff.label :author %>
      <%= ff.text_field :author %>
    </div>
  <% end %>
  <div>
    <% f.object.genres.each do |genre| %>
      <%= fields_for 'comic_genre[genres][]', genre do |ff| %>
        <%= ff.label :name %>
        <%= ff.text_field :name %>
      <% end %>
    <% end %>
  </div>
  <div>
    <%= f.submit '登録' %>
  </div>
<% end %>

app/views/comics/edit.html.erb
<%= render 'form' %>

<% breadcrumb :comic_edit %>
<%= render 'shared/breadcrumb' %>

app/views/comics/index.html.erb
<h1>Comics#index</h1>
<p>Find me in app/views/comics/index.html.erb</p>

<%= link_to '漫画登録', new_comic_path %>

<% @comics.each do |comic| %>
  <div>
    <p><%= "#{Comic.human_attribute_name(:id)}：#{comic.id}" %></p>
    <p><%= "#{Comic.human_attribute_name(:title)}：#{comic.title}" %></p>
    <p><%= "#{Comic.human_attribute_name(:author)}：#{comic.author}" %></p>
    <% comic.genres.each do |genre| %>
      <% if genre.name.present? %> <!-- nilまたは空文字を登録してるジャンルが表示されないようにしてる -->
        <p><%= "#{Genre.human_attribute_name(:name)}：#{genre.name}" %></p>
      <% end %>
    <% end %>
  </div>
  <div><%= link_to '編集する', edit_comic_path(comic) %></div>
<% end %>

<% breadcrumb :comic_index %>
<%= render 'shared/breadcrumb' %>

app/views/comics/new.html.erb
<%= render 'form' %>

<% breadcrumb :comic_new %>
<%= render 'shared/breadcrumb' %>