config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :areas do
    # 単数形リソース(resource)なので通常は単数形で書くが、複数のfoodsを取り扱うため複数形で定義している
    resource :foods, only: [:new, :create, :edit, :update], module: :areas, controller: :foods
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'posts#index'
  resources :comics, except: [:destroy]
  resources :posts, only: [:index] do
    collection do
      get 'google_map'
      post 'sort'
      get 'send_sample_mail'
      get 'send_now_sample_mail'
      get 'csv_export'
      get :zip_export
    end
  end

  namespace :api do
    get 'postal_code_search/search'
  end

  # コマンドでcontrollerファイルをディレクトリ階層いかに生成した場合、以下のようにルーティングが自動記述される。
  # namespace ディレクトリ名でURLを"/ディレクトリ名/コントローラー名", 見に行くコントローラーも"/ディレクトリ名/コントローラー名"になる。実装によってscopeやscope moduleなどを使い分けるとよい
  namespace :hoge do
    # get 'posts/index'
    resources :posts, only: [:index]
  end

  resources :tweets, only: [:index, :new, :create, :edit, :update]

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  mount Sidekiq::Web => '/sidekiq'

  # Bootstrap JavaScript Bundle with Popper
  direct :bootstrap_javascript do
    'https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js'
  end
  # Bootstrap Icons
  direct :bootstrap_icons_css do
    'https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css'
  end

  # Slick(JavaScriptはimportmapで導入)
  direct :slick_css do
    'https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css'
  end
  direct :slick_theme_css do
    'https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css'
  end
end

app/models/area.rb
class Area < ApplicationRecord
  has_many :foods, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/controllers/areas/foods_controller.rb
module Areas
  class FoodsController < ApplicationController
    before_action :set_area

    def new
      @food_form = FoodForm.new(area: @area)
    end

    def create
      @food_form = FoodForm.new(food_form_params, area: @area)
      if @food_form.save
        redirect_to area_path(@area)
      else
        render :new
      end
    end

    def edit
      @food_form = FoodForm.new(area: @area)
    end

    def update
      @food_form = FoodForm.new(food_form_params, area: @area)
      if @food_form.update(food_form_params)
        redirect_to area_path(@area)
      else
        # エラーメッセージをフロントに表示させたい場合は
        # @food_form.errors.full_messages または 配下のfoodsもバリデーションチェックをしてるので
        # @food_form.foods.each { |food| food.errors.full_messages }で取り出せる
        render :edit
      end
    end

    private

    def set_area
      @area = Area.find(params[:area_id])
    end

    def food_form_params
      params.require(:food_form).permit(:consent, foods: [:id, :area_id, :name, :price, { tag_ids: [] }])
    end
  end
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: %i[show edit update destroy]

  # GET /areas or /areas.json
  def index
    @areas = Area.all
  end

  # GET /areas/1 or /areas/1.json
  def show; end

  # GET /areas/new
  def new
    @area = Area.new
  end

  # GET /areas/1/edit
  def edit; end

  # POST /areas or /areas.json
  def create
    @area = Area.new(area_params)

    respond_to do |format|
      if @area.save
        format.html { redirect_to area_url(@area), notice: 'Area was successfully created.' }
        format.json { render :show, status: :created, location: @area }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1 or /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to area_url(@area), notice: 'Area was successfully updated.' }
        format.json { render :show, status: :ok, location: @area }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1 or /areas/1.json
  def destroy
    @area.destroy

    respond_to do |format|
      format.html { redirect_to areas_url, notice: 'Area was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_area
    @area = Area.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def area_params
    params.require(:area).permit(:name)
  end
end

app/views/areas/_area.html.erb
<div id="<%= dom_id area %>">
  <p>
    <strong><%= Area.human_attribute_name(:name) %>：</strong>
    <%= area.name %>
  </p>

</div>

app/views/areas/_form.html.erb
<%= form_with(model: area) do |form| %>
  <% if area.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(area.errors.count, "error") %> prohibited this area from being saved:</h2>

      <ul>
        <% area.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/areas/edit.html.erb
<h1>Editing area</h1>

<%= render "form", area: @area %>

<br>

<div>
  <%= link_to "Show this area", @area %> |
  <%= link_to "Back to areas", areas_path %>
</div>

<% breadcrumb :area_edit, @area %>
<%= render 'shared/breadcrumb' %>

app/views/areas/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Areas</h1>

<div id="areas">
  <% @areas.each do |area| %>
    <%= render area %>
    <p>
      <%= link_to "Show this area", area %>
    </p>
  <% end %>
</div>

<%= link_to "New area", new_area_path %>

<% breadcrumb :area_index %>
<%= render 'shared/breadcrumb' %>

app/views/areas/new.html.erb
<h1>New area</h1>

<%= render "form", area: @area %>

<br>

<div>
  <%= link_to "Back to areas", areas_path %>
</div>

<% breadcrumb :area_new %>
<%= render 'shared/breadcrumb' %>

app/views/areas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @area %>

<div>
  <h3><%= Food.model_name.human %></h3>
  <% @area.foods.each do |food| %>
    <div>
      <%= "#{Food.human_attribute_name(:name)}：#{food.name}" %>
    </div>
    <div>
      <%= "#{Food.human_attribute_name(:price)}：#{food.price.to_formatted_s(:delimited)}円" %>
    </div>
    <div>
      <%= "#{Tag.human_attribute_name(:name)}" %>
    </div>
    <div>
      <%= food.tags.pluck(:name).map { |tag_name| "##{tag_name}" }.join('、') %>
    </div>
  <% end %>
</div>

<div>
  <%= link_to "Edit this area", edit_area_path(@area) %> |
  <%= link_to "Back to areas", areas_path %> |
  <%= link_to '食品登録', new_area_foods_path(@area) if @area.foods.blank? %>
  <%= link_to '食品編集', edit_area_foods_path(@area) if @area.foods.present? %>

  <%= button_to "Destroy this area", @area, method: :delete %>
</div>

<% breadcrumb :area_show, @area %>
<%= render 'shared/breadcrumb' %>