config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :areas do
    # 単数形リソース(resource)なので通常は単数形で書くが、複数のfoodsを取り扱うため複数形で定義している
    resource :foods, only: [:new, :create, :edit, :update], module: :areas, controller: :foods
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'posts#index'
  resources :comics, except: [:destroy]
  resources :posts, only: [:index] do
    collection do
      get 'google_map'
      post 'sort'
      get 'send_sample_mail'
      get 'send_now_sample_mail'
      get 'csv_export'
      get :zip_export
    end
  end

  namespace :api do
    get 'postal_code_search/search'
  end

  # コマンドでcontrollerファイルをディレクトリ階層いかに生成した場合、以下のようにルーティングが自動記述される。
  # namespace ディレクトリ名でURLを"/ディレクトリ名/コントローラー名", 見に行くコントローラーも"/ディレクトリ名/コントローラー名"になる。実装によってscopeやscope moduleなどを使い分けるとよい
  namespace :hoge do
    # get 'posts/index'
    resources :posts, only: [:index]
  end

  resources :tweets, only: [:index, :new, :create, :edit, :update]

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  mount Sidekiq::Web => '/sidekiq'

  # Bootstrap JavaScript Bundle with Popper
  direct :bootstrap_javascript do
    'https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js'
  end
  # Bootstrap Icons
  direct :bootstrap_icons_css do
    'https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css'
  end

  # Slick(JavaScriptはimportmapで導入)
  direct :slick_css do
    'https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css'
  end
  direct :slick_theme_css do
    'https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css'
  end
end

app/models/post.rb
class Post < ApplicationRecord
  before_create :set_sort_priority
  after_destroy :reset_sort_priority

  def set_sort_priority
    lowest_priority = Post.maximum(:sort_priority)
    self.sort_priority = lowest_priority.nil? ? 0 : lowest_priority + 1
  end

  def self.reset_sort_priority_by_id
    num = 0
    order(:id).each do |post|
      post.update(sort_priority: num)
      num += 1
    end
  end

  def reset_sort_priority
    num = 0
    Post.order(:sort_priority).each do |post|
      post.update(sort_priority: num)
      num += 1
    end
  end

  def update_sort_priority(old_index, new_index)
    return if old_index == new_index

    sort_range = (old_index - new_index).negative? ? old_index..new_index : new_index..old_index
    index_change = (old_index - new_index).negative? ? -1 : 1
    posts = Post.where(sort_priority: sort_range)

    posts.each do |post|
      next if post.sort_priority == old_index

      post.sort_priority = post.sort_priority + index_change
      post.save
    end

    self.sort_priority = new_index
    save
  end
end

app/controllers/hoge/posts_controller.rb
class Hoge::PostsController < ApplicationController
  def index
    @posts = Post.all
  end
end

app/controllers/posts_controller.rb
require 'csv'
require 'zip'

class PostsController < ApplicationController
  def index
    @posts = Post.order(:sort_priority).limit(10)
    @posts_limit10 = Post.all.limit(10)
    logger.info "Postのタイトル: #{@posts.first.title}" if @posts.present?
  end

  def google_map; end

  def sort
    post = Post.find_by(sort_priority: params[:oldIndex].to_i)
    post.update_sort_priority(params[:oldIndex].to_i, params[:newIndex].to_i)
  end

  def send_sample_mail
    SampleMailer.sample_notice('test@example.com').deliver_later
    redirect_to action: :index
  end

  def send_now_sample_mail
    SampleMailer.sample_notice('test@example.com').deliver_now
    redirect_to action: :index
  end

  def csv_export
    posts = Post.order(:sort_priority)
    csv_string = csv_generate(posts)
    send_data(csv_string, filename: "#{create_filename}.csv")
  end

  def zip_export
    redirect_to action: :index and return if request.format.symbol != :zip

    posts = Post.order(:sort_priority)
    filename = create_filename
    files = generate_csv_files(posts, filename)

    zip_filename = "#{filename}.zip"
    zip_generate(zip_filename, files)
    files.each { |f| File.delete(f) }
    send_data(File.read(zip_filename), filename: zip_filename)
    File.delete(zip_filename)
  end

  private

  # csv文字列の生成
  def csv_generate(posts)
    CSV.generate do |csv|
      csv << %w[title text]
      posts.each { |post| csv << [post.title, post.text] }
    end
  end

  def create_filename
    "posts_#{Time.current.strftime('%Y%m%d%H%M%S')}"
  end

  # csvファイルの生成
  def generate_csv_files(posts, filename)
    file = File.new("#{filename}.csv", 'w+')
    file.write(csv_generate(posts))

    file2 = File.new("#{filename}-2.csv", 'w+')
    file2.write(csv_generate(posts))
    [file, file2]
  end

  # zipファイルの生成
  def zip_generate(zip_filename, files)
    password = Zip::TraditionalEncrypter.new('password') # zipファイルのパスワード生成用インスタンス
    # password = nil
    Zip::OutputStream.open(zip_filename, password) do |out| # passwordがnilまたは引数なしの場合はパスワードなしで生成
      files.each do |file|
        out.put_next_entry(file.path) # zipファイルへの書き込み宣言。
        out.write(File.read(file)) # 上記で宣言したパスへの書き込み
      end
    end
  end
end

app/helpers/hoge/posts_helper.rb
module Hoge::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_slider_posts.html.erb
<%# 最低限必要なのはスライダー全体としての親クラス(下記の例だとclass="your-class") %>
<%# それとスライド1枚1枚としての子要素(下記の例だとclass="slide") %>
<%# タグやクラス名やIDに縛りは特にない(ulとli要素などでもOK) %>

<%# <div class="your-class">
  <div class="slide">
    <div class="content-wrap">
      <div>your content1</div>
      <div>
        <p>Good Morning</p>
      </div>
    </div>
  </div>
  <div class="slide">
    <div class="content-wrap">
      <div>your content2</div>
      <div>
        <p>Good Afternoon</p>
      </div>
    </div>
  </div>
  <div class="slide">
    <div class="content-wrap">
      <div>your content3</div>
      <div>
        <p>Good Evening</p>
      </div>
    </div>
  </div>
  <div class="slide">
    <div class="content-wrap">
      <div>your content4</div>
      <div>
        <p>Hello World</p>
      </div>
    </div>
  </div>
</div> %>


<%# 応用(rubyの繰り返しを絡めた実装) %>

<div class="your-class">
  <% @posts_limit10.each do |post| %>
    <div class="slide">
      <div class="content-wrap">
        <p>タイトル： <%= post.title %></p>
        <p>本文： <%= post.text %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/google_map.html.erb
<!--The div element for the map -->
<div id="map"></div>

<% breadcrumb :google_map %>
<%= render 'shared/breadcrumb' %>

<!-- google api -->
<script async defer src="https://maps.googleapis.com/maps/api/js?key=<%= google_map_api_key %>&callback=initMap"></script>
<script>
  // Initialize and add the map
  function initMap() {
    // The location of Uluru
    const uluru = { lat: -25.344, lng: 131.031 };
    // The map, centered at Uluru
    const map = new google.maps.Map(document.getElementById("map"), {
      zoom: 4,
      center: uluru,
    });
    // The marker, positioned at Uluru
    const marker = new google.maps.Marker({
      position: uluru,
      map: map,
    });
  }
</script>

app/views/posts/index.html.erb
<% content_for :css do %>
  <%= stylesheet_link_tag slick_css_url %>
  <%= stylesheet_link_tag slick_theme_css_url %>
  <%= stylesheet_link_tag bootstrap_icons_css_url %>
<% end %>
<% content_for :javascript do %>
  <%= javascript_include_tag bootstrap_javascript_url %>
<% end %>

<div>
  <%= link_to "郵便番号API利用", api_postal_code_search_search_path %>
</div>
<div>
  <%= link_to '漫画一覧ページ', comics_path %>
</div>
<div>
  <%= link_to 'google map', google_map_posts_path %>
</div>
<div>
  <%= link_to 'ツイート', tweets_path %>
</div>
<div>
  <%= link_to '地域', areas_path %>
</div>
<div>
  <%= link_to 'サンプルメール送信(非同期)', send_sample_mail_posts_path %>
</div>
<div>
  <%= link_to 'サンプルメール送信(同期)', send_now_sample_mail_posts_path %>
</div>
<div>
  <%= link_to 'csvダウンロード', csv_export_posts_path(format: :csv) %>
</div>
<div>
  <%= link_to 'zipダウンロード', zip_export_posts_path(format: :zip) %>
</div>

<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

<%= render partial: 'slider_posts' %>

<h1><%= Post.model_name.human %></h1>
<div id="sortable" style="width: 80vw; margin: 0 auto;" data-sort-url="<%= sort_posts_path %>">
  <% @posts.each do |post| %>
    <div class="d-flex align-items-center">
      <i class="bi bi-grid-3x2-gap me-3 sort-handle"></i>
      <div>
        <p><%= "#{Post.human_attribute_name(:title)}: #{post.title}" %></p>
        <p><%= Post.human_attribute_name(:text) %></p>
        <p style="overflow-wrap: break-word;"><%= post.text %></p>
        <p><%= "#{Post.human_attribute_name(:created_at)}: #{l(post.created_at)}" %></p>
      </div>
    </div>
  <% end %>
</div>

<style>
  .sort-handle {
    cursor: grab;
  }
  .sort-handle:active {
    cursor: grabbing;
  }
</style>